printMainMenu:-
  nl,nl,nl,nl,nl,nl,nl,
  write('        |----------------------------------------------------------------|'),nl,
  write('        |                                                                |'),nl,
  write('        |                                                                |'),nl,
  write('        |  _____                             _____         _  _          |'),nl,
  write('        | |      ___   __ __ ____ _____     |     | _____ | || | _____   |'),nl,
  write('        | |     |   | |  |  |    |     |    |-----|/_____|| || ||     |  |'),nl,
  write('        | |_____|___|_|  |  |____|_____|    |_____||_____ |_||_||_____|  |'),nl,
  write('        |                   |                                            |'),nl,
  write('        |                                                                |'),nl,
  write('        |                                                                |'),nl,
  write('        |                   Choose an option, please!                    |'),nl,
  write('        |                                                                |'),nl,
  write('        |                  1.Start Game Player vs Player                 |'),nl,
  write('        |                                                                |'),nl,
  write('        |                    2.Start Game PC vs Player                   |'),nl,
  write('        |                                                                |'),nl,
	write('        |                      3.Start Game PC vs PC                     |'),nl,
	write('        |                                                                |'),nl,
  write('        |                         4.How to Play                          |'),nl,
  write('        |                                                                |'),nl,
  write('        |                             5.Exit                             |'),nl,
  write('        |                                                                |'),nl,
  write('        |----------------------------------------------------------------| '),nl,nl,nl,nl.
