printMainMenu:-
  nl,nl,nl,
  write('         ___________________________________________________________________________________________'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |  _____   ______   _    _   ______   ______     ______   ______   __       __      ______  |'),nl,
  write('        | |  ___| |  __  | | |  | | |  __  | |  __  |   |  __  | |  ____| |  |     |  |    |  __  | |'),nl,
  write('        | | |     | |__| | | |__| | | |__| | | |  | |   | |__| | | |____  |  |     |  |    | |  | | |'),nl,
  write('        | | |     | |__| | | |  | | |  ____| | |  | |   |  __  | |  ____| |  |     |  |    | |  | | |'),nl,
  write('        | | |___  | |  | | | |  | | | |      | |__| |   | |__| | | |____  |  |___  |  |___ | |__| | |'),nl,
  write('        | |_____| |_|  |_| |_|  |_| |_|      |______|   |______| |______| |______| |______||______| |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                 Choose an option, please!                                 |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                               1.Start Game Player vs Player                               |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                 2.Start Game PC vs Player                                 |'),nl,
  write('        |                                                                                           |'),nl,
	write('        |                                   3.Start Game PC vs PC                                   |'),nl,
	write('        |                                                                                           |'),nl,
  write('        |                                       4.How to Play                                       |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                           5.Exit                                          |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |                                                                                           |'),nl,
  write('        |___________________________________________________________________________________________| '),nl,nl,nl,nl.


  printHowToPlayMenu:-
    nl,nl,nl,
    write('         _____________________________________________________________________________'),nl,
    write('        |                                                                             |'),nl,
    write('        |                                                                             |'),nl,
    write('        |                                                                             |'),nl,
    write('        |             _   _                 _         ______ _                        |'),nl,
    write('        |            | | | |               | |        | ___ | |                       |'),nl,
    write('        |            | |_| | _____      __ | |_ ___   | |_/ / | __ _ _   _            |'),nl,
    write('        |            |  _  |/ _  |  /| / / | __/ _  |  |  __/| |/ _` | | | |          |'),nl,
    write('        |            | | | | (_) | V  V /  | || (_) | | |   | | (_| | |_| |           |'),nl,
    write('        |            |_| |_/|___/ |_/|_/   | __|___/  |_|   |_||__,_||__, |           |'),nl,
    write('        |                                                             __/ |           |'),nl,
    write('        |                                                             |___/           |'),nl,
    write('        |                                                                             |'),nl,
    write('        |    In this game, each player tries to remove as much as possible from their |'),nl,
    write('        |of the board. In turn, the player must jump with his piece to another and if |'),nl,
    write('        |the piece that jumped is one of yours, you should remove it from the game.   |'),nl,
    write('        |Otherwise, if it is one of the adversaries, then you can remove any of your  |'),nl,
    write('        |pieces ohe board (including the one used in the jump).                       |'),nl,
    write('        |    Each player can "chain" up to 3 jumps with the same piece of but you can |'),nl,
    write('        |not jump over it twice. The piece with which the player jumps can not occupy |'),nl,
    write('        |the same space during the same move. If not can jump, the player can ignore  |'),nl,
    write('        |his turn. The game continues even that a player has no more pieces on the    |'),nl,
    write('        |board or no player can make a real leap.                                     |'),nl,
    write('        |    At the end of the game, each player gets 1 point for each of their pieces|'),nl,
    write('        |out of your starting area and 3 points for each piece that is in your area of|'),nl,
    write('        |match. The player with the lowest number of points wins.                     |'),nl,
    write('        |                                                                             |'),nl,
    write('        |                                                                             |'),nl,
    write('        |                             1. Main Menu                                    |'),nl,
    write('        |_____________________________________________________________________________| '),nl,nl,nl,nl.
