
  validateMove('areaX1',LastCol,LastRow,Ncol,Nrow,Board) :- user_is(Curr_user),
                                                  mode_game(Curr_mode),
                                                  if_then_else((LastCol==5,LastRow==3),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  (if_then_else((Ncol==7,Nrow==5),false,
                                                  (Ncol is LastCol+2,
                                                   Nrow is LastRow+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty'))),true),
                                                   (Ncol is LastCol+2,
                                                    Nrow is LastRow+2,
                                                    getPiece(Board,Nrow,Ncol,Piece),
                                                    Piece\='empty'));
                                                   (Ncol is LastCol,
                                                   Nrow is LastRow+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty');
                                                   if_then_else((LastCol==5,LastRow==4),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                   if_then_else((Ncol==7,Nrow==4),false,
                                                   (Nrow is LastRow,
                                                   Ncol is LastCol+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty')),true),
                                                   (Nrow is LastRow,
                                                   Ncol is LastCol+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty')).

  validateMove('areaX2',LastCol,LastRow,Ncol,Nrow,Board) :- user_is(Curr_user),
                                                  mode_game(Curr_mode),
                                                  if_then_else((LastCol==5,LastRow==4),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==7,Nrow==4),false,
                                                  (Ncol is LastCol+2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  (Ncol is LastCol+2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty');
                                                  if_then_else((LastCol==2,LastRow==5),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==4,Nrow==3),false,
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  if_then_else((LastCol==3,LastRow==5),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  (if_then_else((Ncol==5,Nrow==3),false,
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'))),true),
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')).


    validateMove('areaY1',LastCol,LastRow,Ncol,Nrow,Board) :-
                                                  user_is(Curr_user),
                                                  mode_game(Curr_mode),
                                                  if_then_else(Ncol@>9,false,true),
                                                  if_then_else((LastCol==7,LastRow==5),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  (if_then_else((Ncol==5,Nrow==7),false,
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'))),true),
                                                  (if_then_else((LastCol==8,LastRow==5),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  (if_then_else((Ncol==6,Nrow==7),false,
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'))),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'))));
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty');
                                                  if_then_else((LastCol==6,LastRow==5),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==6,Nrow==7),false,
                                                  (Nrow is LastRow+2,
                                                  Ncol is LastCol,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  (Nrow is LastRow+2,
                                                  Ncol is LastCol,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),
                                                  (Nrow is LastRow+2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty').


    validateMove('areaY2',LastCol,LastRow,Ncol,Nrow,Board) :-
                                                  mode_game(Curr_mode),
                                                  user_is(Curr_user),
                                                  if_then_else(Ncol@>9,false,true),
                                                  if_then_else((LastCol==5,LastRow==8),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==3,Nrow==6),false,
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  if_then_else((LastCol==5,LastRow==7),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  (if_then_else((Ncol==3,Nrow==5),false,
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'))),true),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')));
                                                  if_then_else((LastCol==6,LastRow==7),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==6,Nrow==5),false,
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  if_then_else((LastCol==5,LastRow==5),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==3,Nrow==6),false,
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  if_then_else((LastCol==5,LastRow==6),if_then_else((Curr_mode == 1;Curr_user=='player'),
                                                  if_then_else((Ncol==3,Nrow==6),false,
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')),true),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'))).

  listOfValidMoves('areaX1',LastCol,LastRow,Ncol,Nrow,Board) :- if_then_else((LastCol==5,LastRow==3),
                                                                ((Nrow is LastRow+2,
                                                                Ncol is LastCol+2,
                                                                getPiece(Board,Nrow,Ncol,Piece),
                                                                Piece\='empty');
                                                                (Nrow is LastRow+2,
                                                                Ncol is LastCol,
                                                                getPiece(Board,Nrow,Ncol,Piece),
                                                                Piece\='empty')),
                                                                ((Ncol is LastCol+2,
                                                                Nrow is LastRow+2,
                                                                getPiece(Board,Nrow,Ncol,Piece),
                                                                Piece\='empty');
                                                                (Nrow is LastRow,
                                                                Ncol is LastCol+2,
                                                                getPiece(Board,Nrow,Ncol,Piece),
                                                                Piece\='empty');
                                                                (Nrow is LastRow+2,
                                                                Ncol is LastCol,
                                                                getPiece(Board,Nrow,Ncol,Piece),
                                                                Piece\='empty'))),
                                                                if_then_else((LastCol==5,LastRow==4)
                                                                


                                                  user_is(Curr_user),
                                                  mode_game(Curr_mode),
                                                  if_then_else((LastCol==5,LastRow==3),
                                                  (Ncol is LastCol+2,
                                                   Nrow is LastRow+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty',
                                                   if_then_else((Ncol==7,Nrow==5),false,true)),
                                                   (Ncol is LastCol+2,
                                                    Nrow is LastRow+2,
                                                    getPiece(Board,Nrow,Ncol,Piece),
                                                    Piece\='empty'));
                                                   if_then_else((LastCol==5,LastRow==4),
                                                   (Nrow is LastRow,
                                                   Ncol is LastCol+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty',
                                                   if_then_else((Ncol==7,Nrow==4),false,true)),
                                                   (Nrow is LastRow,
                                                   Ncol is LastCol+2,
                                                   getPiece(Board,Nrow,Ncol,Piece),
                                                   Piece\='empty')).

  listOfValidMoves('areaX2',LastCol,LastRow,Ncol,Nrow,Board) :- user_is(Curr_user),
                                                  mode_game(Curr_mode),
                                                  if_then_else((LastCol==5,LastRow==4),
                                                  (Ncol is LastCol+2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==7,Nrow==4),false,true)),
                                                  (Ncol is LastCol+2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty');
                                                  if_then_else((LastCol==2,LastRow==5),
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==4,Nrow==3),false,true)),
                                                  if_then_else((LastCol==3,LastRow==5),
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==5,Nrow==3),false,true)),
                                                  true),
                                                  (Nrow is LastRow-2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')).


    listOfValidMoves('areaY1',LastCol,LastRow,Ncol,Nrow,Board) :-
                                                  user_is(Curr_user),
                                                  mode_game(Curr_mode),
                                                  if_then_else(Ncol@>9,false,true),
                                                  if_then_else((LastCol==7,LastRow==5),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==5,Nrow==7),false,true)),
                                                  if_then_else((LastCol==8,LastRow==5),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==6,Nrow==7),false,true)),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')));
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty');
                                                  if_then_else((LastCol==6,LastRow==5),
                                                  (Nrow is LastRow+2,
                                                  Ncol is LastCol,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==6,Nrow==7),false,true)),
                                                  (Nrow is LastRow+2,
                                                  Ncol is LastCol,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  (Nrow is LastRow+2,
                                                  Ncol is LastCol+2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty').


    listOfValidMoves('areaY2',LastCol,LastRow,Ncol,Nrow,Board) :-
                                                  mode_game(Curr_mode),
                                                  user_is(Curr_user),
                                                  if_then_else(Ncol@>9,false,true),
                                                  if_then_else((LastCol==5,LastRow==8),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==3,Nrow==6),false,
                                                  if_then_else((LastCol==5,LastRow==7),
                                                  if_then_else((Ncol==3,Nrow==5),false,true),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')))),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  if_then_else((LastCol==6,LastRow==7),
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==6,Nrow==5),false,true)),
                                                  (Ncol is LastCol,
                                                  Nrow is LastRow-2,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty'));
                                                  if_then_else((LastCol==5,LastRow==5),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty',
                                                  if_then_else((Ncol==3,Nrow==6),false,
                                                  if_then_else((LastCol==5,LastRow==6),
                                                  if_then_else((Ncol==3,Nrow==6),false,true),true))),
                                                  (Ncol is LastCol-2,
                                                  Nrow is LastRow,
                                                  getPiece(Board,Nrow,Ncol,Piece),
                                                  Piece\='empty')).
